basyx:
  cors:
    allowed-origins: '*'
    allowed-methods: GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
spring:
  data:
    mongodb:
      host: mongo
      port: 27017
      database: aas-registry
      authentication-database: admin
      username: mongoAdmin
      password: mongoPassword
