FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir paho-mqtt jsonschema numpy

# Copy all Python files
COPY MQTT_PackML_Stations/*.py ./

# Define entrypoint with a default command that can be overridden
ENTRYPOINT ["python"]