services:

################################## PACKML STATIONS AND MODULES ###############################
  filling_station:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: filling_station

  camera_station:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: camera_station

      
  stoppering_station:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: stoppering_station


  load_station:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: load_station


  unload_station:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: unload_station