include:
  - compose/docker-compose.basyx.yml
  - compose/docker-compose.kg.yml
  - compose/docker-compose.services.yml
  - compose/docker-compose.simulated-stations.yml

#################¤ NETWORKS AND VOLUMES ####################
networks:
  hivemq-network:
    driver: bridge