version: '3.8'

services:
  emqx-broker:
    image: emqx/emqx:latest
    container_name: emqx-broker
    ports:
      - "1883:1883"
      - "8083:8083"
      - "8084:8084"
      - "8080:8080"
      - "18083:18083"
    networks:
      - emqx-network

  emqx-neuronex:
    image: emqx/neuronex:latest
    privileged: true
    container_name: emqx-neuronex
    ports:
      - "8085:8085"
    networks:
      - emqx-network

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    ports:
      - "1880:1880"
    networks:
      - emqx-network

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    networks:
      - emqx-network

  timescaledb:
    image: timescale/timescaledb:latest-pg12
    container_name: timescaledb
    environment:
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_USER: youruser
      POSTGRES_DB: yourdb
    ports:
      - "5432:5432"
    networks:
      - emqx-network

networks:
  emqx-network:
    driver: bridge

volumes:
  portainer_data: