services:
  hivemq-broker:
    image: eclipse-mosquitto
    container_name: hivemq-broker
    volumes:
      - ./Mosquitto/config:/mosquitto/config:rw
      - ./Mosquitto/data:/mosquitto/data:rw
      - ./Mosquitto/log:/mosquitto/log:rw
    restart: unless-stopped
    ports:
      - "1883:1883" #default mqtt port
      - "9001:9001" #default mqtt port for websockets
    networks:
      - hivemq-network

  frontend:
    build:
      context: ./Configurator
      dockerfile: Dockerfile.frontend
      target: dev
    ports:
      - "5173:5173"
    volumes:
      - ./Configurator:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - VITE_MQTT_BROKER_HOST=${EXTERNAL_HOST:-localhost}
      - VITE_MQTT_BROKER_PORT=${MQTT_WS_PORT:-9001}
      - VITE_AAS_REPOSITORY_URL=http://${EXTERNAL_HOST:-localhost}:8081
      - VITE_AAS_SHELL_REGISTRY_URL=http://${EXTERNAL_HOST:-localhost}:8082
    networks:
      - hivemq-network
    depends_on:
      - hivemq-broker
    restart: unless-stopped

  mqtt-explorer:
    image: smeagolworms4/mqtt-explorer
    container_name: mqtt-explorer
    volumes:
      - ./MQTT-Explorer/config:/mqtt-explorer/config
    ports:
      - "4000:4000"
    environment:
      - HTTP_PORT=4000
      - CONFIG_PATH=/mqtt-explorer/config
    networks:
      - hivemq-network
    depends_on:
      - hivemq-broker
    restart: unless-stopped
    
  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./Portainer/data:/data
    ports:
      - "9000:9000"
    networks:
      - hivemq-network
    restart: unless-stopped

  bt_controller:
    build:
      context: .
      dockerfile: BT_Controller/dockerfile
    container_name: bt_controller
    environment:
      - MQTT_BROKER=${MQTT_BROKER:-hivemq-broker}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - AAS_SERVER=${AAS_SERVER:-aas-env}
      - AAS_PORT=${AAS_PORT:-8081}
      - AAS_REGISTRY=${AAS_REGISTRY:-aas-registry}
      - AAS_REGISTRY_PORT=${AAS_REGISTRY_PORT:-8080}
    volumes:
      - ./BT_Controller/config:/AP2030-UNS/BT_Controller/config
      - ./BTDescriptions:/AP2030-UNS/MQTTSchemas
      - ./AASDescriptions:/AP2030-UNS/AASDescriptions
    ports:
    - "1667:1667"
    networks:
      - hivemq-network
    depends_on:
      hivemq-broker:
        condition: service_started
      registration-service:
        condition: service_healthy

  planar_controller:
    build:
      context: ./Planar_Controller
      dockerfile: Dockerfile
    container_name: planar_controller
    environment:
      - MQTT_BROKER=${MQTT_BROKER:-hivemq-broker}
      - MQTT_PORT=${MQTT_PORT:-1883}
      - PMC_IP=${PMC_IP:-192.168.0.199}
    volumes:
      - ./MQTTSchemas:/app/MQTTSchemas
      - ./AASDescriptions:/app/AASDescriptions
    networks:
      - hivemq-network
    depends_on:
      hivemq-broker:
        condition: service_started
      aas-env:
        condition: service_started
      databridge:
        condition: service_started
      registration-service:
        condition: service_healthy
    restart: unless-stopped

  production_planner:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: production_planner
    networks:
      - hivemq-network
    depends_on:
      hivemq-broker:
        condition: service_started
      aas-env:
        condition: service_started
      databridge:
        condition: service_started
      registration-service:
        condition: service_healthy

  load_station:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: load_station
    networks:
      - hivemq-network
    depends_on:
      hivemq-broker:
        condition: service_started
      aas-env:
        condition: service_started
      databridge:
        condition: service_started
      registration-service:
        condition: service_healthy

  unload_station:
    extends:
      file: ./PackML_Stations/stations-compose.yml
      service: unload_station
    networks:
      - hivemq-network
    depends_on:
      hivemq-broker:
        condition: service_started
      aas-env:
        condition: service_started
      databridge:
        condition: service_started
      registration-service:
        condition: service_healthy



################################### BASYX CONTAINERS ####################################

  aas-env:
    image: eclipsebasyx/aas-environment:2.0.0-SNAPSHOT
    container_name: aas-env
    environment:
      - SERVER_PORT=8081
      - EXTERNAL_HOST=${EXTERNAL_HOST:-localhost}
      - BASYX_BACKEND=InMemory
      - BASYX_ENVIRONMENT=file:aas
      - BASYX_CORS_ALLOWED_ORIGINS=*
      - BASYX_CORS_ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
      - BASYX_AASREPOSITORY_FEATURE_REGISTRYINTEGRATION=http://aas-registry:8080
      - BASYX_SUBMODELREPOSITORY_FEATURE_REGISTRYINTEGRATION=http://sm-registry:8080
      - BASYX_EXTERNALURL=http://${EXTERNAL_HOST:-localhost}:8081
      - SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=500MB
      - SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=500MB
    volumes:
      - ./aas:/application/aas
    ports:
      - '8081:8081'
    restart: always
    depends_on:
      aas-registry:
        condition: service_healthy
      sm-registry:
        condition: service_healthy
      hivemq-broker:
        condition: service_started
    networks:
      - hivemq-network
  aas-registry:
    image: eclipsebasyx/aas-registry-log-mem:2.0.0-SNAPSHOT
    container_name: aas-registry
    ports:
      - '8082:8080'
    environment:
      - SERVER_PORT=8080
      - BASYX_CORS_ALLOWED_ORIGINS=*
      - BASYX_CORS_ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
    restart: always
    networks:
      - hivemq-network
  sm-registry:
    image: eclipsebasyx/submodel-registry-log-mem:2.0.0-SNAPSHOT
    container_name: sm-registry
    ports:
      - '8083:8080'
    environment:
      - SERVER_PORT=8080
      - BASYX_CORS_ALLOWED_ORIGINS=*
      - BASYX_CORS_ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
    restart: always
    networks:
      - hivemq-network
  aas-discovery:
    image: eclipsebasyx/aas-discovery:2.0.0-SNAPSHOT
    container_name: aas-discovery
    environment:
      - SERVER_PORT=8081
      - SPRING_APPLICATION_NAME=AAS Discovery Service
      - BASYX_AASDISCOVERYSERVICE_NAME=aas-discovery-service
      - BASYX_BACKEND=InMemory
      - BASYX_CORS_ALLOWED_ORIGINS=*
      - BASYX_CORS_ALLOWED_METHODS=GET,POST,PATCH,DELETE,PUT,OPTIONS,HEAD
    ports:
      - '8084:8081'
    restart: always
    networks:
      - hivemq-network
  aas-web-ui:
    image: eclipsebasyx/aas-gui:SNAPSHOT
    container_name: aas-ui
    ports:
      - '3000:3000'
    environment:
      AAS_REGISTRY_PATH: http://${EXTERNAL_HOST:-localhost}:8082/shell-descriptors
      SUBMODEL_REGISTRY_PATH: http://${EXTERNAL_HOST:-localhost}:8083/submodel-descriptors
      AAS_REPO_PATH: http://${EXTERNAL_HOST:-localhost}:8081/shells
      SUBMODEL_REPO_PATH: http://${EXTERNAL_HOST:-localhost}:8081/submodels
      CD_REPO_PATH: http://${EXTERNAL_HOST:-localhost}:8081/concept-descriptions
      AAS_DISCOVERY_PATH: http://${EXTERNAL_HOST:-localhost}:8084/lookup/shells
      LOGO_PATH: novo logo.png
      PRIMARY_COLOR: '#0036AA'
      DASHBOARD_SERVICE_PATH: http://${EXTERNAL_HOST:-localhost}:8085/api/elements
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy
    volumes:
      - ./logo:/usr/src/app/dist/Logo
    networks:
      - hivemq-network
  databridge:
    image: eclipsebasyx/databridge:1.0.0-milestone-08
    container_name: databridge
    volumes:
      - ./databridge:/usr/share/config
    restart: always
    depends_on:
      aas-env:
        condition: service_healthy
      hivemq-broker:
        condition: service_started
    networks:
      - hivemq-network
  
  registration-service:
    build:
      context: .
      dockerfile: ./Registration_Service/Dockerfile
    container_name: registration-service
    environment:
      - PYTHONUNBUFFERED=1
      - BASYX_URL=http://${AAS_SERVER:-aas-env}:${AAS_PORT:-8081}
      - MQTT_BROKER=${MQTT_BROKER:-hivemq-broker}
      - MQTT_PORT=${MQTT_PORT:-1883}
      # Delegation URL for BaSyx to call - must be reachable from aas-env container
      - DELEGATION_SERVICE_URL=http://registration-service:8087
      - EXTERNAL_HOST=${EXTERNAL_HOST:-localhost}
      - AAS_SERVER_URL=http://${AAS_SERVER:-aas-env}:${AAS_PORT:-8081}
      - AAS_BASE_URL=https://smartproductionlab.aau.dk
    volumes:
      # DataBridge config directory for writing configs
      - ./databridge:/databridge
      # AAS configs for registration
      - ./AASDescriptions/Resource/configs:/app/configs:ro
      # MQTT Schemas for schema-based message generation
      - ./MQTTSchemas:/app/MQTTSchemas:ro
      # Docker socket for container restarts (DataBridge)
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      # Operation Delegation HTTP API port
      - '8087:8087'
    command:
      - python
      - unified-registration-service.py
      - --mqtt-broker
      - ${MQTT_BROKER:-hivemq-broker}
      - --mqtt-port
      - "${MQTT_PORT:-1883}"
      - --basyx-url
      - http://${AAS_SERVER:-aas-env}:${AAS_PORT:-8081}
      - --delegation-url
      - ${DELEGATION_SERVICE_URL:-http://localhost:8087}
      - listen
      - --delegation-port
      - "8087"
    restart: unless-stopped
    depends_on:
      hivemq-broker:
        condition: service_started
      aas-env:
        condition: service_started
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8087/health || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 12
      start_period: 10s
    networks:
      - hivemq-network


#################¤ NETWORKS AND VOLUMES ####################
networks:
  hivemq-network:
    driver: bridge