imaLoadingSystem2AAS:
    idShort: imaLoadingSystem2AAS
    id: 'https://smartproductionlab.aau.dk/aas/imaLoadingSystem2AAS'
    globalAssetId: 'https://smartproductionlab.aau.dk/assets/ZDNlYmVhZjItZTAyMC00NWMwLTg5NjEtODRiNTFkOWE0NzVl2'
    derivedFrom: 'https://smartproductionlab.aau.dk/aas/templates/resource'
    assetType: 'https://smartproductionlab.aau.dk/Resource/CPPM/LoadingSystem/imaLoadingSystem'
    serialNumber: 'IMA-LS-2024-001'
    location: 'InnoLab, Nybrovej, AAU'
    AssetInterfacesDescription:
        InterfaceMQTT:
            Title: 'IMA Loading System'
            EndpointMetadata:
                base: 'mqtt://192.168.0.104:1883/NN/Nybrovej/InnoLab/Loading'
                contentType: 'application/json'
            InteractionMetadata:
                actions:
                    -   Loading:
                        key: 'Loading'
                        title: 'Loading'
                        synchronous: 'false'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Loading'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'
                            response:
                                contentType: 'application/json'
                                href: '/DATA/Loading'
                                mqv_controlPacket: 'publish'
                                mqv_retain: 'false'
                    -   Halt:
                        key: 'Halt'
                        title: 'Halt'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Halt'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'                                   
                    -   Occupy:
                        key: 'Occupy'
                        title: 'Occupy'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Occupy'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'
                            response:
                                contentType: 'application/json'
                                href: '/DATA/Occupy'
                                mqv_controlPacket: 'publish'
                                mqv_retain: 'false'
                    -   Release:
                        key: 'Release'
                        title: 'Release'
                        synchronous: 'true'
                        input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/CMD/Release'
                            op: 'invokeAction'
                            mqv_retain: 'false'
                            mqv_controlPacket: subscribe
                            mqv_qos: '2'
                            response:
                                contentType: 'application/json'
                                href: '/DATA/Release'
                                mqv_controlPacket: 'publish'
                                mqv_retain: 'false'
                properties:
                    -   StationState:
                        key: 'StationState'
                        title: 'StationState'
                        output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/stationState.schema.json'
                        forms:
                            contentType: 'application/json'
                            href: '/DATA/State'
                            mqv_retain: 'true'
                            mqv_controlPacket: publish
                            mqv_qos: '0'

    Variables:
        - PackMLState:
            semanticId: 'https://www.omac.org/packml/state'
            InterfaceReference:
                Name: 'StationState'
                Field: 'State'
        - OccupationState:
            semanticId: 'https://smartproductionlab.aau.dk/stationOccupation'
            InterfaceReference: 
                Name: 'StationState'
                Field: 'ProcessQueue'

    Parameters:

    HierarchicalStructures:
        Name: 'BillOfMaterials'
        Archetype: 'OneUp'
        IsPartOf:
            aauFillingLineAAS:
                globalAssetId: 'https://smartproductionlab.aau.dk/assets/MWQ2ODY5ZDEtZTQ3Yy00NWU4LTlmYTAtNTI3YjVlMDk4MWFi'
    
    Capabilities:
        Loading:
            realizedBy: "Load"
            semantic_id: https://smartproductionlab.aau.dk/Capability/Loading

    TransformationData:
        -   Operational:
            semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Predicates/Operational"
            parameters:
                -   name: "Resource"
                    reference:
                        external: "https://smartproductionlab.aau.dk/Resource"  
            transformation: 'parameter1.Variables.PackMLState.State == "Execute"'
        -   Occupied:
            semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Predicates/Occupied"
            parameters:
                -   name: "Resource"
                    reference:
                        external: "https://smartproductionlab.aau.dk/Resource"  
                -   name: "Product"
                    reference:
                        external: "https://smartproductionlab.aau.dk/Product"  
            transformation: 'parameter1.Variables.OccupationState.ProcessQueue[0] == parameter2.Parameters.Uuid'
    
    Skills:
        Loading:
            description: "Loading function for pharmaceutical primary packaging"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Loading"
            InterfaceReference: "Loading"
            skill_desription:
                parameters:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Parameters"
                    parameters:
                        -   name: "LoadingSystem"
                            reference:
                                model:
                                - AAS: "https://smartproductionlab.aau.dk/assets/ZDNlYmVhZjItZTAyMC00NWMwLTg5NjEtODRiNTFkOWE0NzVl2"
                        -   name: "Product"
                            reference:
                                external: "https://smartproductionlab.aau.dk/Product"                        
                        -   name: "TransportSystem"
                            reference:
                                external: "https://smartproductionlab.aau.dk/CPS/Transport"

                conditions:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Conditions"
                    PreConditions:
                        terms:
                            - logicterm:
                                semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Logic/And"
                                terms:
                                    -   fluent:
                                        reference:
                                            model:
                                                -   SM: "OperationalData"
                                                -   SMC: "TransformationData"
                                                -   SMC: "Operational"
                                        parameters:
                                            -   0
                                    -   fluent:
                                        reference:
                                            model:
                                                -   SM: "OperationalData"
                                                -   SMC: "TransformationData"
                                                -   SMC: "Occupied"
                                        parameters:
                                            -   0
                                            -   1
                                        
                effects:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Effects"
                    EndEffects:
                        terms:
                            - logicterm:
                                semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Logic/And"
                                terms:
                                    -   fluent:
                                        reference:
                                            external: "https://smartproductionlab.aau.dk/PDDL/Term/Predicates/On"
                                        parameters:
                                            -   1
                                            -   2
                                    -   fluent:
                                        reference:
                                            external: "https://smartproductionlab.aau.dk/PDDL/Term/Predicates/At"
                                        parameters:
                                            -   1
                                            -   0

        Halt:
            description: "Halt the current operation"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Halt"
            InterfaceReference: "Halt"

        Occupy:
            description: "Occupy the system for exclusive use"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Occupy"
            InterfaceReference: "Occupy"
            skill_desription:
                parameters:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Parameters"
                    parameters:
                        -   name: "LoadingSystem"
                            reference:
                                model:
                                - AAS: "https://smartproductionlab.aau.dk/assets/ZDNlYmVhZjItZTAyMC00NWMwLTg5NjEtODRiNTFkOWE0NzVl2"
                        -   name: "Product"
                            reference:
                                external: "https://smartproductionlab.aau.dk/Product"                        
                        -   name: "TransportSystem"
                            reference:
                                external: "https://smartproductionlab.aau.dk/CPS/Transport"
                conditions:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Conditions"
                    PreConditions:
                        terms:
                            -   logicterm:
                                semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Logic/And"
                                terms:
                                    -   fluent:
                                        reference:
                                            model:
                                                -   SM: "OperationalData"
                                                -   SMC: "TransformationData"
                                                -   SMC: "Operational"
                                        parameters:
                                            -   0
                                    -   logicterm:
                                        semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Logic/Not"
                                        terms:
                                        -   fluent:
                                            reference:
                                                model:
                                                    -   SM: "OperationalData"
                                                    -   SMC: "TransformationData"
                                                    -   SMC: "Occupied"
                                            parameters:
                                                -   0
                                                -   1
                effects:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Effects"
                    EndEffects:
                        terms:
                            - logicterm:
                                semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Logic/And"
                                terms:
                                    -   fluent:
                                        reference:
                                            external: "https://smartproductionlab.aau.dk/PDDL/Term/Predicates/Occupied"
                                        parameters:
                                            -   0
                                            -   1
                                        value: true

        Release:
            description: "Release the system from exclusive use"
            semantic_id: "https://smartproductionlab.aau.dk/skills/Release"
            InterfaceReference: "Release"
            skill_desription:
                parameters:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Parameters"
                    parameters:
                        -   name: "LoadingSystem"
                            reference:
                                model:
                                - AAS: "https://smartproductionlab.aau.dk/assets/ZDNlYmVhZjItZTAyMC00NWMwLTg5NjEtODRiNTFkOWE0NzVl2"
                        -   name: "Product"
                            reference:
                                external: "https://smartproductionlab.aau.dk/Product"                        
                        -   name: "TransportSystem"
                            reference:
                                external: "https://smartproductionlab.aau.dk/CPS/Transport"
                conditions:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Conditions"
                    PreConditions:
                        terms:
                            -   logicterm:
                                semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Logic/And"
                                terms:
                                    -   fluent:
                                        reference:
                                            model:
                                                -   SM: "OperationalData"
                                                -   SMC: "TransformationData"
                                                -   SMC: "Operational"
                                        parameters:
                                            -   0
                                    -   fluent:
                                        reference:
                                            model:
                                                -   SM: "OperationalData"
                                                -   SMC: "TransformationData"
                                                -   SMC: "Occupied"
                                        parameters:
                                            -   0
                                            -   1
                effects:
                    semantic_id: "https://smartproductionlab.aau.dk/PDDL/Effects"
                    EndEffects:
                        terms:
                            - logicterm:
                                semantic_id: "https://smartproductionlab.aau.dk/PDDL/Term/Logic/And"
                                terms:
                                    -   fluent:
                                        reference:
                                            external: "https://smartproductionlab.aau.dk/PDDL/Term/Predicates/Occupied"
                                        parameters:
                                            -   0
                                            -   1
                                        value: false