omronCameraSystemAAS:
  idShort: omronCameraSystemAAS
  id: 'https://smartproductionlab.aau.dk/aas/omronCameraSystemAAS'
  globalAssetId: 'https://smartproductionlab.aau.dk/assets/M2VmNjk0OTgtNmE0YS00MzA4LWE4NjMtM2JjZDZjZDhkMTBl'
  derivedFrom: 'https://smartproductionlab.aau.dk/aas/templates/resource'
  assetType: 'https://smartproductionlab.aau.dk/Resource/CPPM/QualityControlSystem/omronCameraSystem'
  serialNumber: 'OMRON-CAM-2024-001'
  location: 'InnoLab, Nybrovej, AAU'
  AssetInterfacesDescription:
    InterfaceMQTT:
      Title: 'optima Camera System'
      EndpointMetadata:
        base: 'mqtt://192.168.0.104:1883/NN/Nybrovej/InnoLab/QualityControl'
        contentType: 'application/json'
      InteractionMetadata:
        actions:
        - key: 'Capture'
          title: 'Capture'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Capture'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: 'application/json'
              href: '/DATA/Capture'
              mqv_controlPacket: 'publish'
              mqv_retain: 'false'
        - key: 'Halt'
          title: 'Halt'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Halt'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
        - key: 'Occupy'
          title: 'Occupy'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Occupy'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: 'application/json'
              href: '/DATA/Occupy'
              mqv_controlPacket: 'publish'
              mqv_retain: 'false'
        - key: 'Release'
          title: 'Release'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Release'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: 'application/json'
              href: '/DATA/Release'
              mqv_controlPacket: 'publish'
              mqv_retain: 'false'
        properties:
        - key: 'StationState'
          title: 'StationState'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/stationState.schema.json'
          forms:
            contentType: 'application/json'
            href: '/DATA/State'
            mqv_retain: 'true'
            mqv_controlPacket: publish
            mqv_qos: '0'
        - key: 'Image'
          title: 'Image'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/image.schema.json'
          forms:
            contentType: 'application/json'
            href: '/DATA/Image'
            mqv_retain: 'false'
            mqv_controlPacket: publish
            mqv_qos: '0'

  Variables:
  - key: PackMLState
    semanticId: 'https://www.omac.org/packml/state'
    InterfaceReference:
      Name: 'StationState'
      Field: 'State'
  - key: OccupationState
    semanticId: 'cssx:StationOccupation'
    InterfaceReference:
      Name: 'StationState'
      Field: 'ProcessQueue'
  - key: Image
    semanticId: 'cssx:ImageData'
    InterfaceReference:
      Name: 'Image'
      Field: 'Image'
  Parameters:
    Location:
      semanticId: 'cssx:LocationParameter'
      value: 'omronCameraStation'
  HierarchicalStructures:
    Name: 'BillOfMaterials'
    Archetype: 'OneUp'
    IsPartOf:
      aauFillingLineAAS:
        globalAssetId: 'https://smartproductionlab.aau.dk/assets/MWQ2ODY5ZDEtZTQ3Yy00NWU4LTlmYTAtNTI3YjVlMDk4MWFi'
  Capabilities:
  - key: Inspection
    realizedBy: "Capture"
    semantic_id: cssx:QualityControlCapability
  - key: Capture
    realizedBy: "Capture"
    semantic_id: cssx:CaptureCapability

  AI-Planning:
    Domain:
        Fluents:
            -   key: "Operational"
                semantic_id: "cssx:Operational"
                parameters:
                    -   name: "Resource"
                        externalRef: "css:Resource"
                transformation: 'parameter1.Variables.PackMLState.State == "Execute"'

            -   key: "Occupied"
                semantic_id: "cssx:Occupied"
                parameters:
                    -   name: "Resource"
                        externalRef: "css:Resource"
                    -   name: "Product"
                        externalRef: "css:Product"
                transformation: 'parameter1.Variables.OccupationState.ProcessQueue[0] == parameter2.Parameters.Uuid'

            -   key: "Free"
                semantic_id: "cssx:Free"
                parameters:
                    -   name: "Resource"
                        externalRef: "css:Resource"
                transformation: 'parameter1.Variables.OccupationState.ProcessQueue == []'

        Actions:
            -   key: "QualityControl"
                semantic_id: "cssx:QualityControlCapability"
                SkillReference: "Capture"
                parameters:
                    -   name: "CameraSystem"
                        modelRef:
                            - AAS: "self"
                    -   name: "Product"
                        externalRef: "css:Product"
                    -   name: "TransportSystem"
                        externalRef: "cssx:Transport"
                    -   name: "CameraLocation"
                        modelRef:
                            - AAS: "self"
                              Submodel: "Parameters"
                              Element: "Location"
                conditions:
                    at_start:
                        - predicate:
                            ref: "Operational"
                            parameters: [0]
                        - predicate:
                            ref: "Occupied"
                            parameters: [0, 1]
                        - predicate:
                            external: "cssx:On"
                            parameters: [1, 2]
                        - predicate:
                            external: "cssx:ProductAt"
                            parameters: [1, 3]
                effects:
                    at_end:
                        - predicate:
                            external: "cssx:Captured"
                            parameters: [1]

            -   key: "Occupy"
                semantic_id: "cssx:OccupyCapability"
                SkillReference: "Occupy"
                parameters:
                    -   name: "CameraSystem"
                        modelRef:
                            - AAS: "self"
                    -   name: "Product"
                        externalRef: "css:Product"
                conditions:
                    at_start:
                        - predicate:
                            ref: "Operational"
                            parameters: [0]
                        - not:
                            predicate:
                                ref: "Occupied"
                                parameters: [0, 1]
                effects:
                    at_end:
                        - predicate:
                            ref: "Occupied"
                            parameters: [0, 1]
                        - not:
                            predicate:
                                ref: "Free"
                                parameters: [0]


            -   key: "Release"
                semantic_id: "cssx:ReleaseCapability"
                SkillReference: "Release"
                parameters:
                    -   name: "CameraSystem"
                        modelRef:
                            - AAS: "self"
                    -   name: "Product"
                        externalRef: "css:Product"
                conditions:
                    at_start:
                        - predicate:
                            ref: "Operational"
                            parameters: [0]
                        - predicate:
                            ref: "Occupied"
                            parameters: [0, 1]
                effects:
                    at_end:
                        - not:
                            - predicate:
                                ref: "Occupied"
                                parameters: [0, 1]
                        - predicate:
                            ref: "Free"
                            parameters: [0]

    Problem:
        Objects:
            -   name: "omronCameraSystem"
                modelRef:
                    - AAS: "self"
            -   name: "captureLocation"
                modelRef:
                    - AAS: "self"
                      Submodel: "Parameters"
                      Element: "Location"

        Init:
            -   predicate:
                ref: "Operational"
                parameters: [0]
            -   predicate:
                ref: "Free"
                parameters: [0]

        Goal:
            - predicate:
                ref: "Operational"
                parameters: [0]
            -   predicate:
                ref: "Free"
                parameters: [0]
    
  Skills:
  - key: Capture
    description: "Capture image for quality control"
    semantic_id: "cssx:CaptureSkill"
    InterfaceReference: Capture
  - key: Halt
    description: "Halt the current operation"
    semantic_id: "cssx:HaltSkill"
    InterfaceReference: Halt
  - key: Occupy
    description: "Occupy the system for exclusive use"
    semantic_id: "cssx:OccupySkill"
    InterfaceReference: Occupy
  - key: Release
    description: "Release the system from exclusive use"
    semantic_id: "cssx:ReleaseSkill"
    InterfaceReference: Release
