omronCameraSystemAAS:
  idShort: omronCameraSystemAAS
  id: https://smartproductionlab.aau.dk/aas/omronCameraSystemAAS
  globalAssetId: https://smartproductionlab.aau.dk/assets/M2VmNjk0OTgtNmE0YS00MzA4LWE4NjMtM2JjZDZjZDhkMTBl
  derivedFrom: https://smartproductionlab.aau.dk/aas/templates/resource
  assetType: http://www.w3id.org/aau-ra/cssx#QualityControlSystem
  serialNumber: OMRON-CAM-2024-001
  location: InnoLab, Nybrovej, AAU
  AssetInterfacesDescription:
    InterfaceMQTT:
      Title: optima Camera System
      EndpointMetadata:
        base: mqtt://192.168.0.104:1883/NN/Nybrovej/InnoLab/QualityControl
        contentType: application/json
      InteractionMetadata:
        actions:
        - key: Capture
          title: Capture
          synchronous: 'true'
          input: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json
          output: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json
          forms:
            contentType: application/json
            href: /CMD/Capture
            op: invokeAction
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: application/json
              href: /DATA/Capture
              mqv_controlPacket: publish
              mqv_retain: 'false'
        - key: Halt
          title: Halt
          synchronous: 'true'
          input: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json
          forms:
            contentType: application/json
            href: /CMD/Halt
            op: invokeAction
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
        - key: Occupy
          title: Occupy
          synchronous: 'true'
          input: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json
          output: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json
          forms:
            contentType: application/json
            href: /CMD/Occupy
            op: invokeAction
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: application/json
              href: /DATA/Occupy
              mqv_controlPacket: publish
              mqv_retain: 'false'
        - key: Release
          title: Release
          synchronous: 'true'
          input: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json
          output: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json
          forms:
            contentType: application/json
            href: /CMD/Release
            op: invokeAction
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: application/json
              href: /DATA/Release
              mqv_controlPacket: publish
              mqv_retain: 'false'
        properties:
        - key: StationState
          title: StationState
          output: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/stationState.schema.json
          forms:
            contentType: application/json
            href: /DATA/State
            mqv_retain: 'true'
            mqv_controlPacket: publish
            mqv_qos: '0'
        - key: Image
          title: Image
          output: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/image.schema.json
          forms:
            contentType: application/json
            href: /DATA/Image
            mqv_retain: 'false'
            mqv_controlPacket: publish
            mqv_qos: '0'
        - key: QualityResult
          title: QualityResult
          output: https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/qualityResult.schema.json
          forms:
            contentType: application/json
            href: /DATA/Quality
            mqv_retain: 'true'
            mqv_controlPacket: publish
            mqv_qos: '2'
  Variables:
  - key: PackMLState
    semanticId: https://w3id.org/2026/apex/semantic/state/operational
    InterfaceReference:
      Name: StationState
      Field: State
  - key: OccupationState
    semanticId: https://w3id.org/2026/apex/semantic/state/occupied
    InterfaceReference:
      Name: StationState
      Field: ProcessQueue
  - key: Image
    semanticId: cssx:ImageData
    InterfaceReference:
      Name: Image
      Field: Image
  - key: QualityResult
    semanticId: cssx:QualityResult
    InterfaceReference:
      Name: QualityResult
  Parameters:
    Location:
      semanticId: https://w3id.org/2026/apex/semantic/location/label
      Position:
        X: 480.0
        Y: 240.0
        Yaw: 0.0
  HierarchicalStructures:
    Name: BillOfMaterials
    Archetype: OneUp
    IsPartOf:
      aauFillingLineAAS:
        globalAssetId: https://smartproductionlab.aau.dk/assets/MWQ2ODY5ZDEtZTQ3Yy00NWU4LTlmYTAtNTI3YjVlMDk4MWFi
  Capabilities:
  - key: Inspection
    realizedBy: Capture
    semantic_id: cssx:QualityControlCapability
  - key: Capture
    realizedBy: Capture
    semantic_id: cssx:CaptureCapability
  Skills:
  - key: Capture
    description: Capture image for quality control
    semantic_id: cssx:CaptureSkill
    InterfaceReference: Capture
    ExecutionModel:
      Parameters:
      - key: CameraSystem
        modelRef:
        - AAS: self
      - key: Product
        semanticId: css:Product
      - key: TransportSystem
        semanticId: cssx:Transport
      - key: CameraLocation
        modelRef:
        - AAS: self
          Submodel: Parameters
          Element: Location
      Conditions:
        PreConditions:
        - predicate: cssx:Operational
          args:
          - 0
        - predicate: cssx:Occupied
          args:
          - 0
          - 1
        - predicate: cssx:On
          args:
          - 1
          - 2
        - predicate: cssx:ProductAt
          args:
          - 1
          - 3
      Effects:
        EndEffects:
        - predicate: cssx:Captured
          args:
          - 1
        - oneOf:
          - when: Result = Ok
            predicate: cssx:QualityOk
            args:
            - 1
          - when: Result != Ok
            not:
            - predicate: cssx:QualityOk
              args:
              - 1
  - key: Halt
    description: Halt the current operation
    semantic_id: cssx:HaltSkill
    InterfaceReference: Halt
  - key: Occupy
    description: Occupy the system for exclusive use
    semantic_id: cssx:OccupySkill
    InterfaceReference: Occupy
    ExecutionModel:
      Parameters:
      - key: CameraSystem
        modelRef:
        - AAS: self
      - key: Identifiable
        semanticId: cssx:Identifiable
      Conditions:
        PreConditions:
        - predicate: cssx:Free
          args:
          - 0
        - predicate: cssx:Occupied
          args:
          - 0
          - 1
          negated: true
      Effects:
        EndEffects:
        - predicate: cssx:Occupied
          args:
          - 0
          - 1
        - predicate: cssx:Free
          args:
          - 0
          negated: true
  - key: Release
    description: Release the system from exclusive use
    semantic_id: cssx:ReleaseSkill
    InterfaceReference: Release
    ExecutionModel:
      Parameters:
      - key: CameraSystem
        modelRef:
        - AAS: self
      - key: Identifiable
        semanticId: cssx:Identifiable
      Conditions:
        PreConditions:
        - predicate: cssx:Operational
          args:
          - 0
        - predicate: cssx:Occupied
          args:
          - 0
          - 1
      Effects:
        EndEffects:
        - predicate: cssx:Occupied
          args:
          - 0
          - 1
          negated: true
        - predicate: cssx:Free
          args:
          - 0
