optimaUnloadingSystemAAS:
  idShort: optimaUnloadingSystemAAS
  id: 'https://smartproductionlab.aau.dk/aas/optimaUnloadingSystemAAS'
  globalAssetId: 'https://smartproductionlab.aau.dk/assets/NGRjZjc0ODUtZTIxMi00ZGQxLWE3MzAtYmEzMDc1NTBlNmMx'
  derivedFrom: 'https://smartproductionlab.aau.dk/aas/templates/resource'
  assetType: 'https://smartproductionlab.aau.dk/Resource/CPPM/UnloadingSystem/optimaUnloadingSystem'
  serialNumber: 'OPTIMA-ULS-2024-001'
  location: 'InnoLab, Nybrovej, AAU'
  AssetInterfacesDescription:
    InterfaceMQTT:
      Title: 'optima Unloading System'
      EndpointMetadata:
        base: 'mqtt://192.168.0.104:1883/NN/Nybrovej/InnoLab/Unloading'
        contentType: 'application/json'
      InteractionMetadata:
        actions:
        - key: 'Unloading'
          title: 'Unloading'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Unloading'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: 'application/json'
              href: '/DATA/Unloading'
              mqv_controlPacket: 'publish'
              mqv_retain: 'false'
        - key: 'Halt'
          title: 'Halt'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Halt'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
        - key: 'Occupy'
          title: 'Occupy'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Occupy'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: 'application/json'
              href: '/DATA/Occupy'
              mqv_controlPacket: 'publish'
              mqv_retain: 'false'
        - key: 'Release'
          title: 'Release'
          synchronous: 'true'
          input: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/command.schema.json'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/commandResponse.schema.json'
          forms:
            contentType: 'application/json'
            href: '/CMD/Release'
            op: 'invokeAction'
            mqv_retain: 'false'
            mqv_controlPacket: subscribe
            mqv_qos: '2'
            response:
              contentType: 'application/json'
              href: '/DATA/Release'
              mqv_controlPacket: 'publish'
              mqv_retain: 'false'
        properties:
        - key: 'StationState'
          title: 'StationState'
          output: 'https://aausmartproductionlab.github.io/AP2030-UNS/MQTTSchemas/stationState.schema.json'
          forms:
            contentType: 'application/json'
            href: '/DATA/State'
            mqv_retain: 'true'
            mqv_controlPacket: publish
            mqv_qos: '0'

  Variables:
  - key: PackMLState
    semanticId: 'https://www.omac.org/packml/state'
    InterfaceReference:
      Name: 'StationState'
      Field: 'State'
  - key: OccupationState
    semanticId: 'cssx:StationOccupation'
    InterfaceReference:
      Name: 'StationState'
      Field: 'ProcessQueue'
  Parameters:
    Location:
      semanticId: 'cssx:LocationParameter'
      value: 'optimaUnloadingStation'
  HierarchicalStructures:
    Name: 'BillOfMaterials'
    Archetype: 'OneUp'
    IsPartOf:
      aauFillingLineAAS:
        globalAssetId: 'https://smartproductionlab.aau.dk/assets/MWQ2ODY5ZDEtZTQ3Yy00NWU4LTlmYTAtNTI3YjVlMDk4MWFi'
  Capabilities:
  - key: Unloading
    realizedBy: "Unload"
    semantic_id: cssx:UnloadingCapability

  AI-Planning:
    Domain:
        Fluents:
            -   key: "Operational"
                semantic_id: "cssx:Operational"
                parameters:
                    -   name: "Resource"
                        externalRef: "css:Resource"
                transformation: 'parameter1.Variables.PackMLState.State == "Execute"'

            -   key: "Occupied"
                semantic_id: "cssx:Occupied"
                parameters:
                    -   name: "Resource"
                        externalRef: "css:Resource"
                    -   name: "Product"
                        externalRef: "css:Product"
                transformation: 'parameter1.Variables.OccupationState.ProcessQueue[0] == parameter2.Parameters.Uuid'

            -   key: "Free"
                semantic_id: "cssx:Free"
                parameters:
                    -   name: "Resource"
                        externalRef: "css:Resource"
                transformation: 'parameter1.Variables.OccupationState.ProcessQueue == []'

        Actions:
            -   key: "Unloading"
                SkillReference: "Unloading"
                parameters:
                    -   name: "UnloadingSystem"
                        modelRef:
                            - AAS: "self"
                    -   name: "Product"
                        externalRef: "css:Product"
                    -   name: "TransportSystem"
                        externalRef: "cssx:Transport"
                        
                conditions:
                    at_start:
                        - predicate:
                            ref: "Operational"
                            parameters: [0]
                        - predicate:
                            ref: "Occupied"
                            parameters: [0, 1]
                        - predicate:
                            external: "cssx:On"
                            parameters: [1, 2]
                        - predicate:
                            external: "cssx:At"
                            parameters: [1, 0]
                effects:
                    at_end:
                        - not:
                            - predicate:
                                external: "cssx:On"
                                parameters: [1, 2]

            -   key: "Occupy"
                SkillReference: "Occupy"
                parameters:
                    -   name: "UnloadingSystem"
                        modelRef:
                            - AAS: "self"
                    -   name: "Product"
                        externalRef: "css:Product"
                conditions:
                    at_start:
                        - predicate:
                            ref: "Operational"
                            parameters: [0]
                        - not:
                            predicate:
                                ref: "Occupied"
                                parameters: [0, 1]
                effects:
                    at_end:
                        - predicate:
                            ref: "Occupied"
                            parameters: [0, 1]
                        - not:
                            predicate:
                                ref: "Free"
                                parameters: [0]


            -   key: "Release"
                SkillReference: "Release"
                parameters:
                    -   name: "UnloadingSystem"
                        modelRef:
                            - AAS: "self"
                    -   name: "Product"
                        externalRef: "css:Product"
                conditions:
                    at_start:
                        - predicate:
                            ref: "Operational"
                            parameters: [0]
                        - predicate:
                            ref: "Occupied"
                            parameters: [0, 1]
                effects:
                    at_end:
                        - not:
                            - predicate:
                                ref: "Occupied"
                                parameters: [0, 1]
                        - predicate:
                            ref: "Free"
                            parameters: [0]

    Problem:
        Objects:
            -   name: "optimaUnloadingSystem"
                modelRef:
                    - AAS: "self"
            -   name: "optimaUnloadingStation"
                modelRef:
                    - AAS: "self"
                      Submodel: "Parameters"
                      Element: "Location"

        Init:
            -   predicate:
                ref: "Operational"
                parameters: [0]
            -   predicate:
                ref: "Free"
                parameters: [0]

        Goal:
            - predicate:
                ref: "Operational"
                parameters: [0]
            -   predicate:
                ref: "Free"
                parameters: [0]

  Skills:
  - key: Unloading
    description: "Unloading function for pharmaceutical primary packaging"
    semantic_id: "cssx:UnloadingSkill"
    InterfaceReference: Unloading
  - key: Halt
    description: "Halt the current operation"
    semantic_id: "cssx:HaltSkill"
    InterfaceReference: Halt
  - key: Occupy
    description: "Occupy the system for exclusive use"
    semantic_id: "cssx:OccupySkill"
    InterfaceReference: Occupy
  - key: Release
    description: "Release the system from exclusive use"
    semantic_id: "cssx:ReleaseSkill"
    InterfaceReference: Release
