FROM ubuntu:jammy

# Avoid prompts during package installation
ENV DEBIAN_FRONTEND=noninteractive

# Install essential build tools and dependencies
RUN apt-get update && apt-get install -y \
    build-essential \
    cmake \
    make \
    git \
    gcc \
    libssl-dev \
    pkg-config \
    uuid-dev \
    libyaml-cpp-dev \
    libfmt-dev \
    libzmq3-dev \
    libsqlite3-dev \
    libgtest-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copy local AP2030UNS repo content and build
WORKDIR /src
COPY ./BT_Controller /src/AP2030-UNS/BT_Controller
COPY ./schemas /src/AP2030-UNS/schemas
WORKDIR /src/AP2030-UNS/BT_Controller
RUN mkdir -p build && cd build && \
    cmake .. && \
    make VERBOSE=1 -j$(nproc)

WORKDIR /src/AP2030-UNS/BT_Controller/build
CMD ["./bt_controller"]