PREFIX arso: <https://w3id.org/2025/arso#>

WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?aas arso:hasDigitalNameplateSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSubmodel ?sm .
  ?sm a arso:DigitalNameplateSubmodel .
  FILTER NOT EXISTS { ?aas arso:hasDigitalNameplateSubmodel ?sm . }
}
;
WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?aas arso:hasHierarchicalStructuresSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSubmodel ?sm .
  ?sm a arso:HierarchicalStructuresSubmodel .
  FILTER NOT EXISTS { ?aas arso:hasHierarchicalStructuresSubmodel ?sm . }
}
;
WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?aas arso:hasAIDSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSubmodel ?sm .
  ?sm a arso:AIDSubmodel .
  FILTER NOT EXISTS { ?aas arso:hasAIDSubmodel ?sm . }
}
;
WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?aas arso:hasSkillsSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSubmodel ?sm .
  ?sm a arso:SkillsSubmodel .
  FILTER NOT EXISTS { ?aas arso:hasSkillsSubmodel ?sm . }
}
;
WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?aas arso:hasCapabilitiesSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSubmodel ?sm .
  ?sm a arso:CapabilitiesSubmodel .
  FILTER NOT EXISTS { ?aas arso:hasCapabilitiesSubmodel ?sm . }
}
;
WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?aas arso:hasOperationalDataSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSubmodel ?sm .
  ?sm a arso:OperationalDataSubmodel .
  FILTER NOT EXISTS { ?aas arso:hasOperationalDataSubmodel ?sm . }
}
;
WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?aas arso:hasParametersSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSubmodel ?sm .
  ?sm a arso:ParametersSubmodel .
  FILTER NOT EXISTS { ?aas arso:hasParametersSubmodel ?sm . }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?aas arso:hasDigitalNameplateSubmodel ?sm .
}
WHERE {
  ?aas arso:hasDigitalNameplateSubmodel ?sm .
  FILTER NOT EXISTS {
    ?aas arso:hasSubmodel ?sm .
    ?sm a arso:DigitalNameplateSubmodel .
  }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?aas arso:hasHierarchicalStructuresSubmodel ?sm .
}
WHERE {
  ?aas arso:hasHierarchicalStructuresSubmodel ?sm .
  FILTER NOT EXISTS {
    ?aas arso:hasSubmodel ?sm .
    ?sm a arso:HierarchicalStructuresSubmodel .
  }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?aas arso:hasAIDSubmodel ?sm .
}
WHERE {
  ?aas arso:hasAIDSubmodel ?sm .
  FILTER NOT EXISTS {
    ?aas arso:hasSubmodel ?sm .
    ?sm a arso:AIDSubmodel .
  }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?aas arso:hasSkillsSubmodel ?sm .
}
WHERE {
  ?aas arso:hasSkillsSubmodel ?sm .
  FILTER NOT EXISTS {
    ?aas arso:hasSubmodel ?sm .
    ?sm a arso:SkillsSubmodel .
  }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?aas arso:hasCapabilitiesSubmodel ?sm .
}
WHERE {
  ?aas arso:hasCapabilitiesSubmodel ?sm .
  FILTER NOT EXISTS {
    ?aas arso:hasSubmodel ?sm .
    ?sm a arso:CapabilitiesSubmodel .
  }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?aas arso:hasOperationalDataSubmodel ?sm .
}
WHERE {
  ?aas arso:hasOperationalDataSubmodel ?sm .
  FILTER NOT EXISTS {
    ?aas arso:hasSubmodel ?sm .
    ?sm a arso:OperationalDataSubmodel .
  }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?aas arso:hasParametersSubmodel ?sm .
}
WHERE {
  ?aas arso:hasParametersSubmodel ?sm .
  FILTER NOT EXISTS {
    ?aas arso:hasSubmodel ?sm .
    ?sm a arso:ParametersSubmodel .
  }
}
