PREFIX aas:  <https://admin-shell.io/aas/3/1/>
PREFIX arso: <https://w3id.org/2025/arso#>
PREFIX css:  <http://www.w3id.org/hsu-aut/css#>
PREFIX aas-key: <https://admin-shell.io/aas/3/1/Key/>
PREFIX aas-ref: <https://admin-shell.io/aas/3/1/Reference/>
PREFIX aas-rel: <https://admin-shell.io/aas/3/1/RelationshipElement/>
PREFIX aas-rfb: <https://admin-shell.io/aas/3/1/Referable/>
PREFIX aas-sem: <https://admin-shell.io/aas/3/1/HasSemantics/>
PREFIX aas-sm: <https://admin-shell.io/aas/3/1/Submodel/>
PREFIX aas-smc: <https://admin-shell.io/aas/3/1/SubmodelElementCollection/>
PREFIX aas-sml: <https://admin-shell.io/aas/3/1/SubmodelElementList/>

WITH {{ABOX_GRAPH_N3}}
INSERT {
  ?capability css:isRealizedBySkill ?skill .
}
WHERE {
  ?shell arso:hasCapabilitiesSubmodel ?capsSm ;
         arso:hasSkillsSubmodel ?skillsSm .

  ?capsSm (aas-sm:submodelElements|aas-smc:value|aas-sml:value)+ ?realizedByList .

  ?realizedByList a aas:SubmodelElementList ;
                  aas-sem:semanticId ?realizedBySemanticRef ;
                  aas-sml:value ?rel .

  ?realizedBySemanticRef aas-ref:keys ?realizedBySemanticKey .
  ?realizedBySemanticKey aas-key:value "https://admin-shell.io/idta/CapabilityDescription/CapabilityRealizedBy/1/0" .

  ?rel a aas:RelationshipElement ;
       aas-rel:first ?firstRef ;
       aas-rel:second ?secondRef .

  ?firstRef aas-ref:keys ?firstKey .
  ?firstKey aas-key:value ?capContainerIdShort .

  ?capsSm (aas-sm:submodelElements|aas-smc:value|aas-sml:value)+ ?capContainer .
  ?capContainer a aas:SubmodelElementCollection ;
                aas-rfb:idShort ?capContainerIdShort ;
                aas-smc:value ?capability .

  ?capability a aas:Capability .

  ?secondRef aas-ref:keys ?secondKey .
  ?secondKey aas-key:value ?skillIdShort .

  ?skillsSm (aas-sm:submodelElements|aas-smc:value|aas-sml:value)+ ?skill .
  ?skill a aas:SubmodelElementCollection ;
         aas-rfb:idShort ?skillIdShort .

  FILTER NOT EXISTS { ?capability css:isRealizedBySkill ?skill . }
}
;
WITH {{ABOX_GRAPH_N3}}
DELETE {
  ?capability css:isRealizedBySkill ?skill .
}
WHERE {
  ?capability css:isRealizedBySkill ?skill .
  FILTER NOT EXISTS {
    ?shell arso:hasCapabilitiesSubmodel ?capsSm ;
           arso:hasSkillsSubmodel ?skillsSm .

    ?capsSm (aas-sm:submodelElements|aas-smc:value|aas-sml:value)+ ?realizedByList .

    ?realizedByList a aas:SubmodelElementList ;
                    aas-sem:semanticId ?realizedBySemanticRef ;
                    aas-sml:value ?rel .

    ?realizedBySemanticRef aas-ref:keys ?realizedBySemanticKey .
    ?realizedBySemanticKey aas-key:value "https://admin-shell.io/idta/CapabilityDescription/CapabilityRealizedBy/1/0" .

    ?rel a aas:RelationshipElement ;
         aas-rel:first ?firstRef ;
         aas-rel:second ?secondRef .

    ?firstRef aas-ref:keys ?firstKey .
    ?firstKey aas-key:value ?capContainerIdShort .

    ?capsSm (aas-sm:submodelElements|aas-smc:value|aas-sml:value)+ ?capContainer .
    ?capContainer a aas:SubmodelElementCollection ;
                  aas-rfb:idShort ?capContainerIdShort ;
                  aas-smc:value ?resolvedCapability .

    ?resolvedCapability a aas:Capability .

    ?secondRef aas-ref:keys ?secondKey .
    ?secondKey aas-key:value ?skillIdShort .

    ?skillsSm (aas-sm:submodelElements|aas-smc:value|aas-sml:value)+ ?resolvedSkill .
    ?resolvedSkill a aas:SubmodelElementCollection ;
                   aas-rfb:idShort ?skillIdShort .

    FILTER(?resolvedCapability = ?capability)
    FILTER(?resolvedSkill = ?skill)
  }
}
