#!/usr/bin/env python3
"""
Behavior Tree simulator using py_trees.

Converts BTs generated by ``pr2_to_bt`` into executable ``py_trees``
behaviour trees and simulates them against a PDDL-grounded stochastic
world model with randomly-selected non-deterministic outcomes.

Architecture
------------
- **SimulatedWorld** — holds fluents, applies grounded PDDL actions
  with random outcomes, checks goal satisfaction.  Stored on the
  py_trees blackboard so all behaviours can access it.
- **py_trees behaviours** — ``FluentCondition``, ``ExecuteAction``,
  ``SuccessNode``, ``AlwaysFailure`` mirror the pr2_to_bt leaf nodes.
- **convert_to_pytrees()** — 1:1 structural conversion from
  ``pr2_to_bt.BTNode`` trees into py_trees composites/decorators.
- **run_simulation()** — Monte-Carlo validation: tick the py_trees BT
  over many episodes and report success rate / tick statistics.

Usage
-----
::

    from bt_synthesis.simulator import build_simulator, convert_to_pytrees, run_simulation

    # Build world factory from PDDL
    make_world, action_table, goal_pos, goal_neg, init_fluents = build_simulator(
        domain_pddl, problem_pddl)

    # Convert pr2_to_bt BT → py_trees
    pytree_root = convert_to_pytrees(bt.root)

    # Monte-Carlo validation
    results = run_simulation(bt, domain_pddl, problem_pddl, n_trials=500)
    print(f"Success: {results['success_rate']:.1%}")
"""

from __future__ import annotations

import os
import random
import sys
from dataclasses import dataclass
from typing import Any, Callable, Dict, FrozenSet, List, Optional, Sequence as TypingSequence, Set, Tuple

import py_trees

from .pddl_grounding import And, Primitive, ground_pddl

from .causal import (
    GroundedAction,
    _fondparser_predicate_to_fluent,
    _fondparser_op_to_pr2_name,
    _extract_preconditions,
    _extract_outcomes,
    _extract_goal,
)
from .nodes import (
    BTNode,
    Sequence as BTSequence,
    ReactiveSelector,
    ReactiveSequence,
    Inverter,
    KeepRunningUntilFailure,
    ConditionNode,
    ActionNode,
    SuccessLeaf,
    FailureLeaf,
    ForbiddenActionNode,
    SubTreeRef,
    BehaviorTree,
)


# ===================================================================
#  PDDL-Grounded World Model
# ===================================================================


# GroundedAction from bt_synthesis.causal is used as the action info container.
# (Replaces the former GroundedActionInfo duplicate class.)


OutcomeProbabilityProvider = Callable[[str, GroundedAction], Optional[TypingSequence[float]]]


def _normalize_outcome_weights(
    weights: Optional[TypingSequence[float]],
    n_outcomes: int,
) -> Optional[List[float]]:
    """Return normalized weights or ``None`` when input is unusable."""
    if not weights or len(weights) != n_outcomes:
        return None

    normalized: List[float] = []
    for raw in weights:
        try:
            value = float(raw)
        except (TypeError, ValueError):
            return None
        if value < 0.0:
            return None
        normalized.append(value)

    total = sum(normalized)
    if total <= 0.0:
        return None
    return [w / total for w in normalized]


def build_global_outcome_probability_provider(
    profile: str,
    epsilon: float = 1e-3,
) -> OutcomeProbabilityProvider:
    """Create a global outcome-probability profile.

    Parameters
    ----------
    profile : str
        One of ``uniform``, ``mild_skew``, ``strong_skew``.
    epsilon : float
        Minimum smoothing probability mass for each branch.
    """
    profile_key = (profile or "uniform").strip().lower()
    if profile_key not in {"uniform", "mild_skew", "strong_skew"}:
        raise ValueError(
            f"Unsupported probability profile: {profile}. "
            "Use one of: uniform, mild_skew, strong_skew."
        )

    skew_power = {
        "uniform": 0.0,
        "mild_skew": 1.0,
        "strong_skew": 3.0,
    }[profile_key]
    epsilon = max(0.0, float(epsilon))

    def _provider(_action_name: str, action: GroundedAction) -> Optional[TypingSequence[float]]:
        n_outcomes = len(action.outcomes)
        if n_outcomes <= 1:
            return None
        if skew_power <= 0.0:
            base = [1.0] * n_outcomes
        else:
            # Prefer earlier listed outcomes under skewed profiles.
            base = [float((n_outcomes - i) ** skew_power) for i in range(n_outcomes)]
        if epsilon > 0.0:
            base = [b + epsilon for b in base]
        return base

    return _provider


def _replace_template_tokens(text: str, params: Dict[str, str]) -> str:
    result = str(text)
    for key, value in params.items():
        result = result.replace(f"{{{key}}}", value)
    return result


def _clone_bt_with_params(node: BTNode, params: Dict[str, str]) -> BTNode:
    """Clone a BT subtree while materializing ``{param}`` placeholders."""
    if isinstance(node, ConditionNode):
        return ConditionNode(_replace_template_tokens(node.fluent, params))

    if isinstance(node, ActionNode):
        return ActionNode(_replace_template_tokens(node.action_name, params))

    if isinstance(node, SuccessLeaf):
        return SuccessLeaf()

    if isinstance(node, FailureLeaf):
        return FailureLeaf(name=node.name)

    if isinstance(node, ForbiddenActionNode):
        return ForbiddenActionNode(
            forbidden_action=_replace_template_tokens(node.forbidden_action, params)
        )

    if isinstance(node, Inverter):
        return Inverter(_clone_bt_with_params(node.child, params))

    if isinstance(node, KeepRunningUntilFailure):
        return KeepRunningUntilFailure(
            child=_clone_bt_with_params(node.child, params),
            name=node.name,
        )

    if isinstance(node, ReactiveSelector):
        return ReactiveSelector(
            name=node.name,
            children=[_clone_bt_with_params(c, params) for c in node.children],
        )

    if isinstance(node, ReactiveSequence):
        return ReactiveSequence(
            name=node.name,
            children=[_clone_bt_with_params(c, params) for c in node.children],
        )

    if isinstance(node, BTSequence):
        return BTSequence(
            name=node.name,
            children=[_clone_bt_with_params(c, params) for c in node.children],
        )

    if isinstance(node, SubTreeRef):
        return SubTreeRef(
            template_id=node.template_id,
            params={
                k: _replace_template_tokens(v, params)
                for k, v in node.params.items()
            },
        )

    raise ValueError(f"Unknown BT node type while cloning template: {type(node).__name__}")


class SimulatedWorld:
    """PDDL-grounded stochastic world state.

    Maintains a set of positive fluents (closed-world assumption) and
    applies grounded actions by randomly selecting a non-deterministic
    outcome branch.

    Parameters
    ----------
    initial_fluents : set of str
        PR2-format fluent strings for the initial state.
    action_table : dict
        Mapping from action name → ``GroundedAction``.
    goal_pos, goal_neg : frozenset of str
        Positive / negative goal fluents.
    """

    def __init__(
        self,
        initial_fluents: Set[str],
        action_table: Dict[str, GroundedAction],
        goal_pos: FrozenSet[str],
        goal_neg: FrozenSet[str],
        *,
        rng: Optional[random.Random] = None,
        outcome_probability_provider: Optional[OutcomeProbabilityProvider] = None,
    ):
        self.fluents: Set[str] = set(initial_fluents)
        self.action_table = action_table
        self.goal_pos = goal_pos
        self.goal_neg = goal_neg
        self.goal_reached: bool = False
        self.last_outcome_index: Optional[int] = None
        self._rng = rng or random.Random()
        self._outcome_probability_provider = outcome_probability_provider

    # -- query ---------------------------------------------------------

    def holds(self, literal: str) -> bool:
        """Check whether *literal* holds under closed-world assumption."""
        if literal.startswith("not(") and literal.endswith(")"):
            return literal[4:-1] not in self.fluents
        return literal in self.fluents

    def check_goal(self) -> bool:
        """Return ``True`` when the current state satisfies the goal."""
        return all(f in self.fluents for f in self.goal_pos) and all(
            f not in self.fluents for f in self.goal_neg
        )

    # -- mutation ------------------------------------------------------

    def execute_action(self, action_str: str) -> bool:
        """Apply *action_str* with a uniformly random outcome.

        Returns ``True`` on success, ``False`` if the action is unknown
        or preconditions are not met.
        """
        info = self.action_table.get(action_str)
        if info is None:
            return False

        # Verify preconditions
        for pre in info.preconditions:
            if pre not in self.fluents:
                return False
        for neg_pre in info.neg_preconditions:
            if neg_pre in self.fluents:
                return False

        if not info.outcomes:
            return False

        # Outcome selection (default uniform unless a profile/provider is supplied)
        outcome_idx = self._sample_outcome_index(action_str, info)
        self.last_outcome_index = outcome_idx
        add_set, del_set = info.outcomes[outcome_idx]

        # Apply: delete first, then add
        self.fluents -= del_set
        self.fluents |= add_set
        return True

    def _sample_outcome_index(self, action_str: str, action: GroundedAction) -> int:
        n_outcomes = len(action.outcomes)
        if n_outcomes == 1:
            return 0

        raw_weights: Optional[TypingSequence[float]] = None
        if self._outcome_probability_provider is not None:
            raw_weights = self._outcome_probability_provider(action_str, action)
        weights = _normalize_outcome_weights(raw_weights, n_outcomes)

        if weights is None:
            return self._rng.randint(0, n_outcomes - 1)
        return int(self._rng.choices(range(n_outcomes), weights=weights, k=1)[0])


# ===================================================================
#  py_trees Behaviour Nodes
# ===================================================================

# Blackboard key used by all simulator behaviours to access the world.
_WORLD_KEY = "world"


class FluentCondition(py_trees.behaviour.Behaviour):
    """Succeeds iff a fluent holds in the simulated world.

    Reads the ``SimulatedWorld`` from the py_trees blackboard.
    """

    def __init__(self, fluent: str, name: str = ""):
        super().__init__(name=name or fluent)
        self.fluent = fluent
        self.bb = self.attach_blackboard_client()
        self.bb.register_key(
            key=_WORLD_KEY, access=py_trees.common.Access.READ
        )

    def update(self) -> py_trees.common.Status:
        world: SimulatedWorld = self.bb.get(_WORLD_KEY)
        if world.holds(self.fluent):
            return py_trees.common.Status.SUCCESS
        return py_trees.common.Status.FAILURE


class ExecuteAction(py_trees.behaviour.Behaviour):
    """Executes a grounded action in the simulated world.

    On ``update()``, calls ``world.execute_action(action_name)``
    (which picks a random non-deterministic outcome).
    """

    def __init__(self, action_name: str, name: str = ""):
        super().__init__(name=name or f"Do:{action_name}")
        self.action_name = action_name
        self.bb = self.attach_blackboard_client()
        self.bb.register_key(
            key=_WORLD_KEY, access=py_trees.common.Access.WRITE
        )

    def update(self) -> py_trees.common.Status:
        world: SimulatedWorld = self.bb.get(_WORLD_KEY)
        if world.execute_action(self.action_name):
            return py_trees.common.Status.SUCCESS
        return py_trees.common.Status.FAILURE


class SuccessNode(py_trees.behaviour.Behaviour):
    """Marks the goal as reached and succeeds."""

    def __init__(self):
        super().__init__(name="Success")
        self.bb = self.attach_blackboard_client()
        self.bb.register_key(
            key=_WORLD_KEY, access=py_trees.common.Access.WRITE
        )

    def update(self) -> py_trees.common.Status:
        self.bb.get(_WORLD_KEY).goal_reached = True
        return py_trees.common.Status.SUCCESS


class AlwaysFailure(py_trees.behaviour.Behaviour):
    """Always returns FAILURE (used for forbidden / dead-end nodes)."""

    def __init__(self, name: str = "Fail"):
        super().__init__(name=name)

    def update(self) -> py_trees.common.Status:
        return py_trees.common.Status.FAILURE


class NodeTickCountVisitor(py_trees.visitors.VisitorBase):
    """Counts behaviour visits during a single root tick traversal."""

    def __init__(self):
        super().__init__(full=False)
        self.visited_count = 0

    def initialise(self) -> None:
        self.visited_count = 0

    def run(self, _behaviour: py_trees.behaviour.Behaviour) -> None:
        self.visited_count += 1


# ===================================================================
#  Converter: pr2_to_bt.BTNode → py_trees
# ===================================================================


def convert_to_pytrees(
    node: BTNode,
    *,
    templates: Optional[Dict[str, Tuple[BTNode, List[str]]]] = None,
) -> py_trees.behaviour.Behaviour:
    """Recursively convert a ``pr2_to_bt`` BT into a ``py_trees`` tree.

    Node mapping
    ------------
    ==================== ==========================================
    pr2_to_bt            py_trees
    ==================== ==========================================
    ReactiveSelector     ``Selector(memory=False)``
    Sequence             ``Sequence(memory=True)``
    ReactiveSequence     ``Sequence(memory=False)``
    Inverter             ``decorators.Inverter``
    KeepRunningUntilFailure ``decorators.SuccessIsRunning``
    ConditionNode        ``FluentCondition``
    ActionNode           ``ExecuteAction``
    SuccessLeaf          ``SuccessNode``
    FailureLeaf          ``AlwaysFailure``
    ForbiddenActionNode  ``AlwaysFailure`` (with marker name)
    ==================== ==========================================

    Note: pr2_to_bt's deduplication may share BTNode objects across
    parents.  Since py_trees requires each node to have exactly one
    parent, this function creates fresh py_trees nodes for every
    occurrence.
    """
    if isinstance(node, ReactiveSelector):
        composite = py_trees.composites.Selector(
            name=node.name, memory=False
        )
        for child in node.children:
            composite.add_child(convert_to_pytrees(child, templates=templates))
        return composite

    if isinstance(node, BTSequence):
        composite = py_trees.composites.Sequence(
            name=node.name, memory=True
        )
        for child in node.children:
            composite.add_child(convert_to_pytrees(child, templates=templates))
        return composite

    if isinstance(node, ReactiveSequence):
        composite = py_trees.composites.Sequence(
            name=node.name, memory=False
        )
        for child in node.children:
            composite.add_child(convert_to_pytrees(child, templates=templates))
        return composite

    if isinstance(node, Inverter):
        return py_trees.decorators.Inverter(
            name="Inverter",
            child=convert_to_pytrees(node.child, templates=templates),
        )

    if isinstance(node, KeepRunningUntilFailure):
        return py_trees.decorators.SuccessIsRunning(
            name=node.name or "KeepRunningUntilFailure",
            child=convert_to_pytrees(node.child, templates=templates),
        )

    if isinstance(node, SubTreeRef):
        template_table = templates or {}
        template_entry = template_table.get(node.template_id)
        if template_entry is None:
            raise ValueError(f"Unknown SubTree template id: {node.template_id}")
        template_root, _param_names = template_entry
        expanded = _clone_bt_with_params(template_root, dict(node.params))
        return convert_to_pytrees(expanded, templates=templates)

    if isinstance(node, ConditionNode):
        return FluentCondition(node.fluent)

    if isinstance(node, ActionNode):
        return ExecuteAction(node.action_name)

    if isinstance(node, SuccessLeaf):
        return SuccessNode()

    if isinstance(node, ForbiddenActionNode):
        return AlwaysFailure(name=f"Forbid:{node.forbidden_action}")

    if isinstance(node, FailureLeaf):
        return AlwaysFailure(name=node.name)

    raise ValueError(f"Unknown pr2_to_bt node type: {type(node).__name__}")


# ===================================================================
#  PDDL Grounding → World Factory
# ===================================================================


def build_simulator(domain_pddl: str, problem_pddl: str):
    """Build a BT simulator from raw PDDL text.

    Grounds the domain/problem with ``fondparser`` to extract initial
    state, goal conditions, and all action effects.

    Returns
    -------
    tuple of (make_world, action_table, goal_pos, goal_neg, init_fluents)
        ``make_world()`` → fresh ``SimulatedWorld`` at the initial state.
        ``action_table``  → ``{name: GroundedActionInfo}`` for all
        grounded operators.
    """
    tmpdir = None
    try:
        problem = ground_pddl(domain_pddl, problem_pddl)
    finally:
        pass  # cleanup handled by ground_pddl

    def _lower_set(s):
        return frozenset(f.lower() for f in s)

    # -- initial state -------------------------------------------------
    init_fluents: Set[str] = set()
    if isinstance(problem.init, And):
        for arg in problem.init.args:
            if isinstance(arg, Primitive):
                init_fluents.add(
                    _fondparser_predicate_to_fluent(arg.predicate).lower()
                )
    elif isinstance(problem.init, Primitive):
        init_fluents.add(
            _fondparser_predicate_to_fluent(problem.init.predicate).lower()
        )

    # -- goal ----------------------------------------------------------
    goal_pos_raw, goal_neg_raw = _extract_goal(problem.goal)
    goal_pos = _lower_set(goal_pos_raw)
    goal_neg = _lower_set(goal_neg_raw)

    # -- action table --------------------------------------------------
    action_table: Dict[str, GroundedAction] = {}
    for op in problem.operators:
        pr2_name = _fondparser_op_to_pr2_name(op).lower()
        pos_pre, neg_pre = _extract_preconditions(op.precondition)
        outcomes = _extract_outcomes(op)
        action_table[pr2_name] = GroundedAction(
            name=pr2_name,
            preconditions=_lower_set(pos_pre),
            neg_preconditions=_lower_set(neg_pre),
            outcomes=[(_lower_set(a), _lower_set(d)) for a, d in outcomes],
        )

    def make_world(
        *,
        rng: Optional[random.Random] = None,
        outcome_probability_provider: Optional[OutcomeProbabilityProvider] = None,
    ) -> SimulatedWorld:
        return SimulatedWorld(
            initial_fluents=set(init_fluents),
            action_table=action_table,
            goal_pos=goal_pos,
            goal_neg=goal_neg,
            rng=rng,
            outcome_probability_provider=outcome_probability_provider,
        )

    return make_world, action_table, goal_pos, goal_neg, init_fluents


# ===================================================================
#  High-level Simulation API
# ===================================================================


@dataclass
class SimulationResult:
    """Outcome of a Monte-Carlo BT simulation."""

    successes: int
    failures: int
    timeouts: int
    n_trials: int
    tick_counts: List[int]
    node_tick_counts: List[int]

    @property
    def success_rate(self) -> float:
        return self.successes / self.n_trials if self.n_trials else 0.0

    @property
    def avg_ticks(self) -> float:
        return (
            sum(self.tick_counts) / len(self.tick_counts)
            if self.tick_counts
            else 0.0
        )

    @property
    def avg_node_ticks(self) -> float:
        return (
            sum(self.node_tick_counts) / len(self.node_tick_counts)
            if self.node_tick_counts
            else 0.0
        )

    def summary(self) -> str:
        pct = self.success_rate * 100
        return (
            f"Success: {self.successes}/{self.n_trials} ({pct:.1f}%)  "
            f"Avg ticks: {self.avg_ticks:.1f}  "
            f"Avg node-ticks: {self.avg_node_ticks:.1f}  "
            f"Failures: {self.failures}  Timeouts: {self.timeouts}"
        )


def run_simulation(
    bt: BehaviorTree,
    domain_pddl: str,
    problem_pddl: str,
    n_trials: int = 500,
    max_ticks: int = 5000,
    seed: Optional[int] = None,
    on_episode: Optional[Callable[[int, bool, int, int], None]] = None,
    outcome_probability_provider: Optional[OutcomeProbabilityProvider] = None,
) -> SimulationResult:
    """Run Monte-Carlo BT simulation using py_trees.

    Converts the ``pr2_to_bt`` behaviour tree into a ``py_trees``
    tree, then runs *n_trials* independent episodes.  Each episode
    creates a fresh ``SimulatedWorld`` from the grounded PDDL and
    ticks the tree until the goal is reached, the tree fails, or
    *max_ticks* is exceeded.

    Parameters
    ----------
    bt : BehaviorTree
        The pr2_to_bt behaviour tree to simulate.
    domain_pddl, problem_pddl : str
        Raw PDDL text for world grounding.
    n_trials : int
        Number of independent simulation episodes.
    max_ticks : int
        Maximum ticks per episode before declaring timeout.
    seed : int, optional
        Random seed for reproducibility.
    on_episode : callable, optional
        ``(episode_idx, success, ticks, node_ticks)`` callback after each
        episode. ``node_ticks`` is the total count of visited BT nodes over
        all root ticks in the episode.

    Returns
    -------
    SimulationResult
        Aggregated statistics over all episodes.
    """
    rng = random.Random(seed)

    make_world, _, _, _, _ = build_simulator(domain_pddl, problem_pddl)

    # Convert pr2_to_bt tree → py_trees (once)
    pytree_root = convert_to_pytrees(bt.root, templates=bt.templates)
    tree = py_trees.trees.BehaviourTree(root=pytree_root)
    node_tick_visitor = NodeTickCountVisitor()
    tree.add_visitor(node_tick_visitor)
    tree.setup()

    # Blackboard writer for injecting world state
    writer = py_trees.blackboard.Client(name="Simulator")
    writer.register_key(
        key=_WORLD_KEY, access=py_trees.common.Access.WRITE
    )

    successes = 0
    failures = 0
    timeouts = 0
    tick_counts: List[int] = []
    node_tick_counts: List[int] = []

    for trial in range(n_trials):
        world = make_world(
            rng=rng,
            outcome_probability_provider=outcome_probability_provider,
        )
        writer.set(_WORLD_KEY, world)

        episode_success = False
        episode_ticks = 0
        episode_node_ticks = 0

        for tick in range(1, max_ticks + 1):
            tree.tick()
            episode_ticks = tick
            episode_node_ticks += node_tick_visitor.visited_count

            if world.goal_reached or world.check_goal():
                successes += 1
                tick_counts.append(tick)
                node_tick_counts.append(episode_node_ticks)
                episode_success = True
                break

            if pytree_root.status == py_trees.common.Status.FAILURE:
                failures += 1
                break
        else:
            timeouts += 1

        if on_episode is not None:
            on_episode(trial, episode_success, episode_ticks, episode_node_ticks)

    return SimulationResult(
        successes=successes,
        failures=failures,
        timeouts=timeouts,
        n_trials=n_trials,
        tick_counts=tick_counts,
        node_tick_counts=node_tick_counts,
    )


# ===================================================================
#  Display Utilities
# ===================================================================


def display_pytree(bt: BehaviorTree) -> str:
    """Convert a ``pr2_to_bt`` BT to py_trees and return its ASCII art.

    Uses ``py_trees.display.unicode_tree`` for a compact rendering
    of the tree structure.
    """
    pytree_root = convert_to_pytrees(bt.root, templates=bt.templates)
    return py_trees.display.unicode_tree(root=pytree_root)


def render_pytree_dot(
    bt: BehaviorTree,
    output_path: str,
    with_blackboard_variables: bool = False,
) -> None:
    """Render the py_trees tree to a dot/svg/png file.

    Requires ``graphviz`` to be installed on the system.
    """
    pytree_root = convert_to_pytrees(bt.root, templates=bt.templates)
    py_trees.display.render_dot_tree(
        pytree_root,
        target_directory=os.path.dirname(output_path) or ".",
        name=os.path.splitext(os.path.basename(output_path))[0],
        with_blackboard_variables=with_blackboard_variables,
    )
