version: '3.8'

services:
  
  hivemq-broker:
    image: hivemq/hivemq4:latest
    container_name: hivemq-broker
    volumes:
      - ./config/UNS-config.xml:/opt/hivemq/conf/config.xml   
    ports:
      - "1883:1883"
      - "8080:8080"
      - "8883:8883"
      - "8884:8884"
      - "8081:8081"
  groot:
    build:
      context: ./Groot2
      dockerfile: groot2.dockerfile
    container_name: groot2-web
    ports:
      - "6080:6080"
    networks:
      - hivemq-network
    restart: unless-stopped
    
networks:
  hivemq-network:
    driver: bridge
