FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Install dependencies
RUN pip install --no-cache-dir paho-mqtt jsonschema numpy opencv-python
RUN apt-get update && apt-get install ffmpeg libsm6 libxext6  -y
# Copy all Python files
COPY *.py ./

# Define entrypoint with a default command that can be overridden
ENTRYPOINT ["python"]