name: PlanarMotorsExperiment

services:
  # bt_controller:
  #   build:
  #     context: .
  #     dockerfile: BT_Controller/dockerfile
  #   container_name: bt_controller
  #   network_mode: host
  #   volumes:
  #     - ./MQTTSchemas:/src/planar-motors-experiments/MQTTSchemas
  #   depends_on:
  #     - filling_station
  #     - stoppering_station
  production_planner:
    build:
      context: .
      dockerfile: ./planner.dockerfile
    container_name: production_planner
    environment:
      - MQTT_BROKER=hivemq-broker
      - MQTT_PORT=1883
    volumes:
      - .:/app  # Mount entire directory first
      - ../MQTTSchemas:/app/MQTTSchemas  # Then overlay schemas
      - ../AASDescriptions:/app/AASDescriptions  # Mount AAS configs for registration
      - ../BTDescriptions:/app/BTDescriptions  # Mount BT descriptions for subtree loading
    command: productionPlanner.py

  filling_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: filling_station
    environment:
      - MQTT_BROKER=hivemq-broker
      - MQTT_PORT=1883
    volumes:
      - .:/app  # Mount entire directory first
      - ../MQTTSchemas:/app/MQTTSchemas  # Then overlay schemas
      - ../AASDescriptions:/app/AASDescriptions  # Mount AAS configs for registration
    command: fillingProxy.py

  stoppering_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: stoppering_station
    environment:
      - MQTT_BROKER=hivemq-broker
      - MQTT_PORT=1883
    volumes:
      - .:/app  # Mount entire directory first
      - ../MQTTSchemas:/app/MQTTSchemas  # Then overlay schemas
      - ../AASDescriptions:/app/AASDescriptions  # Mount AAS configs for registration
    command: stopperingProxy.py

  load_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: load_station
    environment:
      - MQTT_BROKER=hivemq-broker
      - MQTT_PORT=1883
    volumes:
      - .:/app  # Mount entire directory first
      - ../MQTTSchemas:/app/MQTTSchemas  # Then overlay schemas
      - ../AASDescriptions:/app/AASDescriptions  # Mount AAS configs for registration
    command: loadProxy.py

  unload_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: unload_station
    environment:
      - MQTT_BROKER=hivemq-broker
      - MQTT_PORT=1883
    volumes:
      - .:/app  # Mount entire directory first
      - ../MQTTSchemas:/app/MQTTSchemas  # Then overlay schemas
      - ../AASDescriptions:/app/AASDescriptions  # Mount AAS configs for registration
    command: unloadProxy.py
    
  camera_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: camera_station
    restart: always
    environment:
      - MQTT_BROKER=hivemq-broker
      - MQTT_PORT=1883
    volumes:
      - .:/app  # Mount entire directory first
      - ../MQTTSchemas:/app/MQTTSchemas  # Then overlay schemas
      - ../AASDescriptions:/app/AASDescriptions  # Mount AAS configs for registration
    devices:
      - /dev/video0:/dev/video0
    command: cameraProxy.py