name: PlanarMotorsExperiment

services:
  # bt_controller:
  #   build:
  #     context: .
  #     dockerfile: BT_Controller/dockerfile
  #   container_name: bt_controller
  #   network_mode: host
  #   volumes:
  #     - ./schemas:/src/planar-motors-experiments/schemas
  #   depends_on:
  #     - filling_station
  #     - stoppering_station

  filling_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: filling_station
    volumes:
      - .:/app  # Mount entire directory first
      - ../MQTTSchemas:/app/MQTTSchemas  # Then overlay schemas
    command: fillingProxy.py

  stoppering_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: stoppering_station
    volumes:
      - ../schemas:/app/schemas
      - .:/app  # Mount entire directory
    command: stopperingProxy.py

  load_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: load_station
    volumes:
      - ../schemas:/app/schemas
      - .:/app  # Mount entire directory
    command: loadProxy.py

  unload_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: unload_station
    volumes:
      - ../schemas:/app/schemas
      - .:/app
    command: unloadProxy.py
    
  camera_station:
    build:
      context: .
      dockerfile: ./dockerfile
    container_name: camera_station
    restart: always
    volumes:
      - ../schemas:/app/schemas
      - .:/app  # Mount entire directory
    devices:
      - /dev/video0:/dev/video0
    command: cameraProxy.py